// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6uU7_WwF1E4w42i01fn-YbbE_Ee2xrGI',
    appId: '1:679662424317:web:dce4e8d2bba4fe9126ae94',
    messagingSenderId: '679662424317',
    projectId: 'dummy-54554',
    authDomain: 'dummy-54554.firebaseapp.com',
    storageBucket: 'dummy-54554.appspot.com',
    measurementId: 'G-74HHHPC1JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWvldDRPLImiazOBqKTODOEuYaWQ_5AKg',
    appId: '1:679662424317:android:0083e0daf368787f26ae94',
    messagingSenderId: '679662424317',
    projectId: 'dummy-54554',
    storageBucket: 'dummy-54554.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1e-Z5jxADfW0hg4r-3CTsf4H_OlFw-As',
    appId: '1:679662424317:ios:c04e30098e17061a26ae94',
    messagingSenderId: '679662424317',
    projectId: 'dummy-54554',
    storageBucket: 'dummy-54554.appspot.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1e-Z5jxADfW0hg4r-3CTsf4H_OlFw-As',
    appId: '1:679662424317:ios:c04e30098e17061a26ae94',
    messagingSenderId: '679662424317',
    projectId: 'dummy-54554',
    storageBucket: 'dummy-54554.appspot.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6uU7_WwF1E4w42i01fn-YbbE_Ee2xrGI',
    appId: '1:679662424317:web:f138524c73de52d526ae94',
    messagingSenderId: '679662424317',
    projectId: 'dummy-54554',
    authDomain: 'dummy-54554.firebaseapp.com',
    storageBucket: 'dummy-54554.appspot.com',
    measurementId: 'G-ER5FCJGM5Q',
  );
}
